global:
  storageClass: nfss1
  ingress:
    enabled: true

directory_watcher:
  image: "registry.gitlab.com/ska-telescope/ska-dlm-client/ska-dlm-client"
  version: "0.1.0-dev.ca4ce2f13"
  directory_to_watch: "/dlm/watch_dir"

ska_dlm:
  fullname: "ska-dlm"
