# Default values for the SKA DLM Client.
# This is a YAML-formatted file.

auth_token: "Replace this with the authorization token"

location:
  name: "local-dev"
  type: "local-dev"
  country: "AU"
  city: "Kensington"
  facility: "local"

storage:
  name: "data1"
  type: "filesystem"
  interface: "posix"
  capacity: 100000000,
  phase_level: "GAS"

DLM:
  url: "http://dlm/api"
